language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
install:
  - pip install . --use-mirrors
  - pip install -r test_requirements.txt --use-mirrors
script:
  - nosetests --with-coverage 2>test_out
after_script:
  - pip install --quiet python-coveralls
  - pip install --quiet coviolations_app
  - coverage report
  - coveralls
  - covio
